language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "tianacleto1"
    token:
      secure: $SONAR_TOKEN

services:
  - mysql

before_install:
  - mysql -u root --password="" < src/test/java/travis.sql

script:
  # other script steps might be done before running the actual analysis
  #- ./mvnw clean install -B
  #- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
